pipeline{
    agent {
       node{
           label "master"
           customWorkspace "/tmp"
       }
    }
    stages{
        stage("Print"){
            steps{
                echo "Hello World"
            }
        }
    }
}