pipeline{
    agent any
    stages{
        stage("Print"){
            steps{
                retry(3){
                    timeout(time: 1, unit: 'SECONDS'){
                        sleep 2
                    }
                    echo 'after timeout'
                }
            }
        }
    }
}